services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
  app:
    build: .
    image: users-app
    ports:
      - 8081:8080
volumes:
   postgres-data: